---
- hosts: all
  become: yes
  become_user: root
    
  tasks:
    - name: Create ansible account
      user:
        name: ansible
        password: "{{ user_pw }}"
        groups: sudo
        append: yes
        state: present

    - name: Add ansible authorized key
      authorized_key:
        user: ansible
        key: "{{ user_pub_key }}"
        state: present
      