---
- hosts: all
  become: yes
    
  tasks:
    - name: Ensure group 'admin' exists
      group:
        name: admin
        state: present

    - name: Create ansible account
      user:
        name: ansible
        password: "{{ user_pw }}"
        groups: admin
        append: yes
        state: present

    - name: Add ansible authorized key
      authorized_key:
        user: ansible
        key: "{{ user_pub_key }}"
        state: present