---
- hosts: all
  become: yes
    
  tasks:
    - name: Create ansible account
      user:
        name: ansible
        password: "!"
        state: present

    - name: Add ansible authorized key
      authorized_key:
        user: ansible
        key: "{{ user_pub_key }}"
        state: present
      
    - name: Configure sudoers
      lineinfile:   
        dest: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) ALL"
        state: present
        create: yes
        validate: "visudo -cf %s"