---
- hosts: all
  become: yes

  tasks:
    - name: Remove previous step-cli install
      ansible.builtin.file:
        path: /usr/local/bin/step
        state: absent

- hosts: all
  become: yes

  vars_files:
    - vars/step.yml
    
  roles:
    - common
    - andrewrothstein.step
    - step-ssh-host