---

- name: Install CIFS and other required packages for mounting with apt
  apt: 
    name: "{{ apt_mount_packages }}"
    update_cache: yes
    force: yes
    state: latest
  when: ansible_os_family == 'Debian'
  tags: packages

- name: Install CIFS and other required packages for mounting with yum
  yum: 
    name: "{{ yum_mount_packages }}"
    update_cache: yes
    force: yes
    state: latest
  when: ansible_os_family == 'RedHat'
  tags: packages

- name: Place Samba credentials file
  template:
    src: .smbcredentials.j2
    dest: "{{ samba_home }}/.smbcredentials"
    owner: "{{ samba_user }}"
    mode: 0600

- name: mount shared drive
  mount:
    fstype: cifs
    state: mounted
    path: "/nfs/{{ item }}"
    opts: "credentials={{ samba_home }}/.smbcredentials,file_mode=0777,dir_mode=0777"
    src: "//{{ cifs_server }}/{{ item }}"
  loop: "{{ cifs_mounts }}"